-- MySQL Script generated by MySQL Workbench
-- 06/01/16 12:56:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd-sistema-gestion-hotelera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd-sistema-gestion-hotelera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd-sistema-gestion-hotelera` DEFAULT CHARACTER SET utf8 ;
USE `bd-sistema-gestion-hotelera` ;

-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`formadepago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`formadepago` (
  `idFormaDePago` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idFormaDePago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`recibo` (
  `idRecibo` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `importe` DOUBLE NULL DEFAULT NULL,
  `idFormaDePago` INT(11) NOT NULL,
  PRIMARY KEY (`idRecibo`),
  INDEX `fk_Recibo_FormaDePago1_idx` (`idFormaDePago` ASC),
  CONSTRAINT `fk_Recibo_FormaDePago1`
    FOREIGN KEY (`idFormaDePago`)
    REFERENCES `bd-sistema-gestion-hotelera`.`formadepago` (`idFormaDePago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`cliente` (
  `idCliente` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `dni` INT(15) NULL DEFAULT NULL,
  `idLogin` INT(11) NOT NULL,
  `idRecibo` INT(11) NOT NULL,
  PRIMARY KEY (`idCliente`, `idLogin`),
  INDEX `fk_Cliente_Recibo1_idx` (`idRecibo` ASC),
  CONSTRAINT `fk_Cliente_Recibo1`
    FOREIGN KEY (`idRecibo`)
    REFERENCES `bd-sistema-gestion-hotelera`.`recibo` (`idRecibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`tipoempleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`tipoempleado` (
  `idTipoEmpleado` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoEmpleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`empleado` (
  `legajo` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `dni` INT(15) NULL DEFAULT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `idTipoEmpleado` INT(11) NOT NULL,
  `empleadocol` VARCHAR(45) NULL,
  PRIMARY KEY (`legajo`, `idTipoEmpleado`),
  INDEX `fk_Empleado_TipoEmpleado1_idx` (`idTipoEmpleado` ASC),
  CONSTRAINT `fk_Empleado_TipoEmpleado1`
    FOREIGN KEY (`idTipoEmpleado`)
    REFERENCES `bd-sistema-gestion-hotelera`.`tipoempleado` (`idTipoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`hotel` (
  `cuil` VARCHAR(13) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `categoria` INT(11) NULL DEFAULT NULL,
  `checkin` VARCHAR(5) NULL DEFAULT NULL,
  `chekout` VARCHAR(5) NULL,
  `idHotel` INT(11) NOT NULL,
  PRIMARY KEY (`cuil`, `idHotel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`contacto` (
  `idContacto` INT(11) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `celular` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idContacto`),
  CONSTRAINT `fk_contacto_empleado`
    FOREIGN KEY (`idContacto`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contacto_cliente`
    FOREIGN KEY (`idContacto`)
    REFERENCES `bd-sistema-gestion-hotelera`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contacto_hotel`
    FOREIGN KEY (`idContacto`)
    REFERENCES `bd-sistema-gestion-hotelera`.`hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`direccion` (
  `idDireccion` INT(11) NOT NULL,
  `calle` VARCHAR(80) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `codigoPostal` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDireccion`),
  CONSTRAINT `fk_direccion_cliente`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `bd-sistema-gestion-hotelera`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_hotel`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `bd-sistema-gestion-hotelera`.`hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`estadia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`estadia` (
  `idEstadia` INT(11) NOT NULL,
  `fechaIngreso` DATE NULL DEFAULT NULL,
  `fechaSalida` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idEstadia`),
  CONSTRAINT `fk_estadia_cliente`
    FOREIGN KEY (`idEstadia`)
    REFERENCES `bd-sistema-gestion-hotelera`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estadia_empleado`
    FOREIGN KEY (`idEstadia`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`estadoestadia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`estadoestadia` (
  `idEstadoEstadia` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEstadoEstadia`),
  CONSTRAINT `fk_estadoEstadia_Estadia`
    FOREIGN KEY (`idEstadoEstadia`)
    REFERENCES `bd-sistema-gestion-hotelera`.`estadia` (`idEstadia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`itemfactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`itemfactura` (
  `idItemFactura` INT(11) NOT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `precioUnitario` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idItemFactura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`factura` (
  `idFactura` INT(11) NOT NULL,
  `fechaEmision` DATE NULL DEFAULT NULL,
  `legajo` INT(11) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  `idItemFactura` INT(11) NOT NULL,
  PRIMARY KEY (`idFactura`, `legajo`),
  INDEX `fk_Factura_Empleado1_idx` (`legajo` ASC),
  INDEX `fk_Factura_Cliente1_idx` (`idCliente` ASC),
  INDEX `fk_Factura_Item1_idx` (`idItemFactura` ASC),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bd-sistema-gestion-hotelera`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Empleado1`
    FOREIGN KEY (`legajo`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Item1`
    FOREIGN KEY (`idItemFactura`)
    REFERENCES `bd-sistema-gestion-hotelera`.`itemfactura` (`idItemFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`tipohabitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`tipohabitacion` (
  `idTipoHabitacion` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoHabitacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`habitacion` (
  `idHabitacion` INT(11) NOT NULL,
  `capacidadMax` INT(11) NULL DEFAULT NULL,
  `disponibilidad` BIT(1) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `idTipoHabitacion` INT(11) NOT NULL,
  PRIMARY KEY (`idHabitacion`),
  INDEX `fk_habitacion_tipohabitacion1_idx` (`idTipoHabitacion` ASC),
  CONSTRAINT `fk_habitacion_tipohabitacion1`
    FOREIGN KEY (`idTipoHabitacion`)
    REFERENCES `bd-sistema-gestion-hotelera`.`tipohabitacion` (`idTipoHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`habitacionestadia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`habitacionestadia` (
  `idHabitacion` INT(11) NOT NULL,
  `idEstadia` INT(11) NOT NULL,
  PRIMARY KEY (`idHabitacion`, `idEstadia`),
  INDEX `fk_Habitacion_has_Estadia_Estadia1_idx` (`idEstadia` ASC),
  INDEX `fk_Habitacion_has_Estadia_Habitacion1_idx` (`idHabitacion` ASC),
  CONSTRAINT `fk_Habitacion_has_Estadia_Estadia1`
    FOREIGN KEY (`idEstadia`)
    REFERENCES `bd-sistema-gestion-hotelera`.`estadia` (`idEstadia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habitacion_has_Estadia_Habitacion1`
    FOREIGN KEY (`idHabitacion`)
    REFERENCES `bd-sistema-gestion-hotelera`.`habitacion` (`idHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`privilegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`privilegio` (
  `idPrivilegio` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPrivilegio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`login` (
  `idLogin` INT(11) NOT NULL,
  `usuario` VARCHAR(100) NULL DEFAULT NULL,
  `clave` VARCHAR(45) NULL DEFAULT NULL,
  `idPrivilegio` INT(11) NOT NULL,
  PRIMARY KEY (`idLogin`, `idPrivilegio`),
  INDEX `fk_Login_Privilegio1_idx` (`idPrivilegio` ASC),
  CONSTRAINT `fk_Login_Privilegio1`
    FOREIGN KEY (`idPrivilegio`)
    REFERENCES `bd-sistema-gestion-hotelera`.`privilegio` (`idPrivilegio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_cliente`
    FOREIGN KEY (`idLogin`)
    REFERENCES `bd-sistema-gestion-hotelera`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_empleado`
    FOREIGN KEY (`idLogin`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`reportelimpieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`reportelimpieza` (
  `idReporteLimpieza` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `desperfeto` VARCHAR(45) NULL DEFAULT NULL,
  `legajo` INT(11) NOT NULL,
  PRIMARY KEY (`idReporteLimpieza`),
  INDEX `fk_ReporteLimpieza_Empleado1_idx` (`legajo` ASC),
  CONSTRAINT `fk_ReporteLimpieza_Empleado1`
    FOREIGN KEY (`legajo`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`reportemantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`reportemantenimiento` (
  `idReporte` INT(11) NOT NULL,
  `reparacion` VARCHAR(45) NULL DEFAULT NULL,
  `fechaOrigen` DATE NULL DEFAULT NULL,
  `fechaResolucion` DATE NULL DEFAULT NULL,
  `desperfecto` VARCHAR(80) NULL DEFAULT NULL,
  `resuelto` BIT(1) NULL DEFAULT NULL,
  `legajo` INT(11) NOT NULL,
  PRIMARY KEY (`idReporte`),
  INDEX `fk_ReporteMantenimiento_Empleado1_idx` (`legajo` ASC),
  CONSTRAINT `fk_ReporteMantenimiento_Empleado1`
    FOREIGN KEY (`legajo`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`tipoticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`tipoticket` (
  `idTipoTicket` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoTicket`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`ticket` (
  `idTicket` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `idFactura` INT(11) NOT NULL,
  `legajo` INT(11) NOT NULL,
  `idTipoTicket` INT(11) NOT NULL,
  `idEstadia` INT(11) NOT NULL,
  PRIMARY KEY (`idTicket`, `legajo`),
  INDEX `fk_Ticket_Factura1_idx` (`idFactura` ASC),
  INDEX `fk_Ticket_Empleado1_idx` (`legajo` ASC),
  INDEX `fk_Ticket_TipoTicket1_idx` (`idTipoTicket` ASC),
  INDEX `fk_ticket_estadia1_idx` (`idEstadia` ASC),
  CONSTRAINT `fk_Ticket_Empleado1`
    FOREIGN KEY (`legajo`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_Factura1`
    FOREIGN KEY (`idFactura`)
    REFERENCES `bd-sistema-gestion-hotelera`.`factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ticket_TipoTicket1`
    FOREIGN KEY (`idTipoTicket`)
    REFERENCES `bd-sistema-gestion-hotelera`.`tipoticket` (`idTipoTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_estadia1`
    FOREIGN KEY (`idEstadia`)
    REFERENCES `bd-sistema-gestion-hotelera`.`estadia` (`idEstadia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`servicio` (
  `idServicio` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idServicio`),
  CONSTRAINT `fk_servicio_ticket`
    FOREIGN KEY (`idServicio`)
    REFERENCES `bd-sistema-gestion-hotelera`.`ticket` (`idTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '		';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
