-- MySQL Script generated by MySQL Workbench
-- 06/11/16 15:14:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd-sistemagestionhotelera
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bd-sistema-gestion-hotelera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd-sistema-gestion-hotelera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd-sistema-gestion-hotelera` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contacto` (
  `idContacto` INT(11) NOT NULL,
  `telParticular` MEDIUMTEXT NULL DEFAULT NULL,
  `telCelular` MEDIUMTEXT NULL DEFAULT NULL,
  `cp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idContacto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direccion` (
  `idDireccion` INT(11) NOT NULL,
  `calle` VARCHAR(80) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `cp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicio` (
  `idServicio` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '		';

USE `bd-sistema-gestion-hotelera` ;

-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`contacto` (
  `idContacto` INT(11) NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `celular` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idContacto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`direccion` (
  `idDireccion` INT(11) NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(80) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `codigoPostal` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`privilegio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`privilegio` (
  `idPrivilegio` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idPrivilegio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`login` (
  `idLogin` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(100) NULL DEFAULT NULL,
  `clave` VARCHAR(45) NULL DEFAULT NULL,
  `idPrivilegio` INT(11) NOT NULL,
  PRIMARY KEY (`idLogin`, `idPrivilegio`),
  INDEX `fk_login_privilegio1_idx` (`idPrivilegio` ASC),
  CONSTRAINT `fk_login_privilegio1`
    FOREIGN KEY (`idPrivilegio`)
    REFERENCES `bd-sistema-gestion-hotelera`.`privilegio` (`idPrivilegio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `dni` INT(15) NULL DEFAULT NULL,
  `idContacto` INT(11) NOT NULL,
  `idDireccion` INT(11) NOT NULL,
  `idLogin` INT(11) NOT NULL,
  PRIMARY KEY (`idCliente`, `idLogin`, `idDireccion`, `idContacto`),
  INDEX `fk_cliente_contacto1_idx` (`idContacto` ASC),
  INDEX `fk_cliente_direccion1_idx` (`idDireccion` ASC),
  INDEX `fk_cliente_login1_idx` (`idLogin` ASC),
  CONSTRAINT `fk_cliente_contacto1`
    FOREIGN KEY (`idContacto`)
    REFERENCES `bd-sistema-gestion-hotelera`.`contacto` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_direccion1`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `bd-sistema-gestion-hotelera`.`direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_login1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `bd-sistema-gestion-hotelera`.`login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`tipoempleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`tipoempleado` (
  `idTipoEmpleado` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoEmpleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`empleado` (
  `legajo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `dni` INT(15) NULL DEFAULT NULL,
  `fechaNacimiento` DATE NULL DEFAULT NULL,
  `idLogin` INT(11) NOT NULL,
  `idContacto` INT(11) NOT NULL,
  `idTipoEmpleado` INT(11) NOT NULL,
  PRIMARY KEY (`legajo`, `idLogin`, `idContacto`, `idTipoEmpleado`),
  INDEX `fk_empleado_login1_idx` (`idLogin` ASC),
  INDEX `fk_empleado_contacto1_idx` (`idContacto` ASC),
  INDEX `fk_empleado_tipoempleado1_idx` (`idTipoEmpleado` ASC),
  CONSTRAINT `fk_empleado_login1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `bd-sistema-gestion-hotelera`.`login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_contacto1`
    FOREIGN KEY (`idContacto`)
    REFERENCES `bd-sistema-gestion-hotelera`.`contacto` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_tipoempleado1`
    FOREIGN KEY (`idTipoEmpleado`)
    REFERENCES `bd-sistema-gestion-hotelera`.`tipoempleado` (`idTipoEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`estadoestadia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`estadoestadia` (
  `idEstadoEstadia` INT(11) NOT NULL,
  PRIMARY KEY (`idEstadoEstadia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`tipoticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`tipoticket` (
  `idTipoTicket` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoTicket`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`servicio` (
  `idServicio` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '		';


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`ticket` (
  `idTicket` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `legajo` INT(11) NOT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `tipoticket_idTipoTicket` INT(11) NOT NULL,
  `idServicio` INT(11) NOT NULL,
  PRIMARY KEY (`idTicket`, `legajo`, `tipoticket_idTipoTicket`),
  INDEX `fk_Ticket_Empleado1_idx` (`legajo` ASC),
  INDEX `fk_ticket_tipoticket1_idx` (`tipoticket_idTipoTicket` ASC),
  INDEX `fk_ticket_servicio1_idx` (`idServicio` ASC),
  CONSTRAINT `fk_Ticket_Empleado1`
    FOREIGN KEY (`legajo`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_tipoticket1`
    FOREIGN KEY (`tipoticket_idTipoTicket`)
    REFERENCES `bd-sistema-gestion-hotelera`.`tipoticket` (`idTipoTicket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_servicio1`
    FOREIGN KEY (`idServicio`)
    REFERENCES `bd-sistema-gestion-hotelera`.`servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`estadia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`estadia` (
  `idEstadia` INT(11) NOT NULL,
  `fechaIngreso` DATE NULL DEFAULT NULL,
  `fechaSalida` DATE NULL DEFAULT NULL,
  `idEstadoEstadia` INT(11) NOT NULL,
  `idTicket` INT(11) NULL DEFAULT NULL,
  `idCliente` INT(11) NOT NULL,
  PRIMARY KEY (`idEstadoEstadia`),
  INDEX `fk_Estadia_TipoEstado1_idx` (`idEstadoEstadia` ASC),
  INDEX `fk_estadia_cliente` (`idEstadia` ASC),
  INDEX `ticketsConstraint` (`idTicket` ASC),
  INDEX `clienteConstraint` (`idCliente` ASC),
  CONSTRAINT `clienteConstraint`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bd-sistema-gestion-hotelera`.`cliente` (`idCliente`),
  CONSTRAINT `estadoEstadiaConstraint`
    FOREIGN KEY (`idEstadoEstadia`)
    REFERENCES `bd-sistema-gestion-hotelera`.`estadoestadia` (`idEstadoEstadia`),
  CONSTRAINT `ticketsConstraint`
    FOREIGN KEY (`idTicket`)
    REFERENCES `bd-sistema-gestion-hotelera`.`ticket` (`idTicket`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`itemfactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`itemfactura` (
  `idItemFactura` INT(11) NOT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `precioUnitario` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idItemFactura`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`factura` (
  `idFactura` INT(11) NOT NULL,
  `fechaEmision` DATE NULL DEFAULT NULL,
  `legajo` INT(11) NOT NULL,
  `idCliente` INT(11) NOT NULL,
  `idItemFactura` INT(11) NOT NULL,
  PRIMARY KEY (`idFactura`, `legajo`),
  INDEX `fk_Factura_Empleado1_idx` (`legajo` ASC),
  INDEX `fk_Factura_Cliente1_idx` (`idCliente` ASC),
  INDEX `fk_Factura_Item1_idx` (`idItemFactura` ASC),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bd-sistema-gestion-hotelera`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Empleado1`
    FOREIGN KEY (`legajo`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Item1`
    FOREIGN KEY (`idItemFactura`)
    REFERENCES `bd-sistema-gestion-hotelera`.`itemfactura` (`idItemFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`formadepago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`formadepago` (
  `idFormaDePago` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idFormaDePago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`habitacion` (
  `idHabitacion` INT(11) NOT NULL,
  `capacidadMaxima` INT(11) NULL DEFAULT NULL,
  `disponibilidad` TINYINT(1) NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idHabitacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`habitacionestadia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`habitacionestadia` (
  `idHabitacion` INT(11) NOT NULL,
  `idEstadia` INT(11) NOT NULL,
  PRIMARY KEY (`idHabitacion`, `idEstadia`),
  INDEX `fk_Habitacion_has_Estadia_Estadia1_idx` (`idEstadia` ASC),
  INDEX `fk_Habitacion_has_Estadia_Habitacion1_idx` (`idHabitacion` ASC),
  CONSTRAINT `fk_Habitacion_has_Estadia_Estadia1`
    FOREIGN KEY (`idEstadia`)
    REFERENCES `bd-sistema-gestion-hotelera`.`estadia` (`idEstadia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habitacion_has_Estadia_Habitacion1`
    FOREIGN KEY (`idHabitacion`)
    REFERENCES `bd-sistema-gestion-hotelera`.`habitacion` (`idHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`hotel` (
  `idHotel` INT(11) NOT NULL AUTO_INCREMENT,
  `cuil` VARCHAR(13) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `categoria` INT(11) NULL DEFAULT NULL,
  `checkIn` VARCHAR(5) NULL DEFAULT NULL,
  `chekOut` VARCHAR(5) NULL,
  `idDireccion` INT(11) NOT NULL,
  PRIMARY KEY (`idHotel`, `cuil`, `idDireccion`),
  INDEX `fk_hotel_direccion1_idx` (`idDireccion` ASC),
  CONSTRAINT `fk_hotel_direccion1`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `bd-sistema-gestion-hotelera`.`direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`recibo` (
  `idRecibo` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `importe` DOUBLE NULL DEFAULT NULL,
  `idCliente` INT(11) NOT NULL,
  `idFormaDePago` INT(11) NOT NULL,
  PRIMARY KEY (`idRecibo`),
  INDEX `fk_recibo_cliente1_idx` (`idCliente` ASC),
  INDEX `fk_recibo_formadepago1_idx` (`idFormaDePago` ASC),
  CONSTRAINT `fk_recibo_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bd-sistema-gestion-hotelera`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recibo_formadepago1`
    FOREIGN KEY (`idFormaDePago`)
    REFERENCES `bd-sistema-gestion-hotelera`.`formadepago` (`idFormaDePago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`reportelimpieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`reportelimpieza` (
  `idReporteLimpieza` INT(11) NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `desperfeto` VARCHAR(45) NULL DEFAULT NULL,
  `legajo` INT(11) NOT NULL,
  PRIMARY KEY (`idReporteLimpieza`),
  INDEX `fk_ReporteLimpieza_Empleado1_idx` (`legajo` ASC),
  CONSTRAINT `fk_ReporteLimpieza_Empleado1`
    FOREIGN KEY (`legajo`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`reportemantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`reportemantenimiento` (
  `idReporte` INT(11) NOT NULL,
  `reparacion` VARCHAR(45) NULL DEFAULT NULL,
  `fechaOrigen` DATE NULL DEFAULT NULL,
  `fechaResolucion` DATE NULL DEFAULT NULL,
  `desperfecto` VARCHAR(80) NULL DEFAULT NULL,
  `terminado` BIT(1) NULL DEFAULT b'0',
  `legajo` INT(11) NOT NULL,
  PRIMARY KEY (`idReporte`),
  INDEX `fk_ReporteMantenimiento_Empleado1_idx` (`legajo` ASC),
  CONSTRAINT `fk_ReporteMantenimiento_Empleado1`
    FOREIGN KEY (`legajo`)
    REFERENCES `bd-sistema-gestion-hotelera`.`empleado` (`legajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd-sistema-gestion-hotelera`.`tipohabitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd-sistema-gestion-hotelera`.`tipohabitacion` (
  `idTipoHabitacion` INT(11) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoHabitacion`),
  CONSTRAINT `fk_tipoHabitacion_Habitacion`
    FOREIGN KEY (`idTipoHabitacion`)
    REFERENCES `bd-sistema-gestion-hotelera`.`habitacion` (`idHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
